### ISSUE TITLE
"Unexpected token )" on the userscripts page

### ISSUE THREAD

**Issue by gunr2171** [Charcoal-SE/charcoal-se.github.io#10]
Right now the Userscripts page says "Loading...", but doesn't complete due to a JavaScript syntax error.

> Uncaught SyntaxError: Unexpected token )
> userscripts.js:6

Seems to come from

    function getMeta(meta,file,)

<sub>Also, sorry, I'm not sure if this should be reported in this repository or in the userscripts repository, seeing that the offending file is [here](https://github.com/Charcoal-SE/userscripts/blob/master/userscripts.js).</sub>

**Comment by Fortunate-MAN** [comment]
"Userscripts page": which page are you talking about? Are you trying to install that US?

**Comment by gunr2171** [comment]
http://charcoal-se.org/userscripts

**Comment by Fortunate-MAN** [comment]
ah, that clarifies it. Looks like I'm a bit outdated on this now.

I'm also getting the same thing, going to make a PR to (maybe) fix this thing. Thanks for reporting!

**Comment by ArtOfCode-** [comment]
Looks fixed to me.
