### ISSUE TITLE
The red color of the autoflagging box is bad.

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/charcoal-se.github.io#11]
Please react with your preference:

* 👍 for the current blue
* 😄 for brown ([#EECCAA](https://duckduckgo.com/?q=%23EECCAA&ia=answer))
* ❤️ for the Bootstrap blue set (text: [#31708F](https://duckduckgo.com/?q=%2331708F&ia=answer), background: [#D9EDF7](https://duckduckgo.com/?q=%23D9EDF7&ia=answer))

**Comment by ArtOfCode-** [comment]
Executive decision based on a 2-1 vote: Bootstrap blue.
