### ISSUE TITLE
Host the SmokeDetector and metasmoke wikis on charcoal-se.org

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/charcoal-se.github.io#12]
It’s possible to host the SmokeDetector and metasmoke wikis on the website. We need several things to get this working:

- [x] Use Travis (or another CI provider) to build the website and include the wikis
- [ ] Use metasmoke’s webhook to run the CI build on each [GollumEvent](https://developer.github.com/v3/activity/events/types/#gollumevent) (wiki update)
- [ ] Make this repo’s default branch `site` or `src`, and autogenerate the `master` branch with the CI
- [x] Move the j-f1/charcoal-jekyll-theme repo to the Charcoal-SE org
- [x] Fix the search page

---

Full task list:

- [x] (me) better build scripts
- [x] (me) Remove the `baseurl` config
- [x] (admin) Enable Travis CI for this repo
- [x] (me) force-push `master` & `site` branches
- [ ] (admin) switch default branch to `site`
-  `await Travis.CI.build()`
- [x] 😄

/cc @Charcoal-SE/websiteers @Charcoal-SE/metasmokers

**Comment by ArtOfCode-** [comment]
Sounds fun. Happy for you to do this, in principle, since you seem to know what you're doing :) Lemme know if you need repo admin or metasmoke changes, etc.

**Comment by Fortunate-MAN** [comment]
I would normally prefer [Read the docs](https://readthedocs.org/) (RTD) for such things if we are going to host it on the website (RTD supports custom domains, in our case something like `docs.charcoal-se.org`). It takes the content directly from the repo (it looks for a specific directory) and supports both `.md` and `.rst`.

Anything else should also work, but in my experience RTD is simple and smooth. You can start builds directly from the website and the docs also look pretty nice.

**Comment by angussidney** [comment]
I think that I remember that @j-f1 said a while ago that if we do this we can integrate the wiki with our own site design. Will RTD allow us to do this @Fortunate-MAN?

**Comment by Fortunate-MAN** [comment]
@angussidney not sure about that. RTD has a lot of site themes you can choose from, but I'm not sure if you can make your own theme. JF did not mention that in the issue so I didn't consider that.

IMO the default theme is pretty good though you can choose another theme. AFAIK you cannot make your own custom theme, though I may be wrong.

**Comment by j-f1** [comment]
Here’s what I’ve got so far: https://j-f1.github.io/charcoal-se.github.io/

**Comment by ArtOfCode-** [comment]
Tangential issue: that menu bar is too wide now. That takes up the full width of the page on my widescreen monitor, so smaller devices have no chance. We should condense that down to some essential links, and put the rest in a submenu somehow.

**Comment by j-f1** [comment]
@ArtOfCode- Fixed.

**Comment by ArtOfCode-** [comment]
That... was quick. Thanks :)
