### ISSUE TITLE
Broken links in title bar on http://charcoal-se.org

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/charcoal-se.github.io#18]
A lot of places in the source seem to use relative URLs which only work on Github and not on charcoal-se.org, or vice versa.

In particular, I notice that the links in the title bar on http://charcoal-se.org/ are mostly broken.

* The home (house) icon links to https://github.com (sic)
* (Chat and "more projects" dropdown are fine.)
* Userscripts links to https://github.com/scripts
* Wiki links to https://github.com/smokey/ (sic)
* API links to a resource in https://github.com/ms/ which is 404

I am unable to figure out where these links are defined, or I would fix them myself.

**Comment by j-f1** [comment]
(Hopefully) fixed by [`44e5875`](https://github.com/Charcoal-SE/charcoal-jekyll-theme/commit/44e58755d592fb1830f2e64e4691429fa62c3677).

**Comment by j-f1** [comment]
Actually fixed by [`61513b4`](https://github.com/Charcoal-SE/charcoal-jekyll-theme/commit/61513b4f22f5c16c6ae298fd64d42d11e982b14a).
