### ISSUE TITLE
Broken link to wiki in Stack Apps profile

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/charcoal-se.github.io#19]
When you click on Smoke Detector's icon in chat, you are offered [its profile page on Stack Apps.](https://softwarerecs.stackexchange.com/users/5072/smokedetector)  This profile contains a broken link to the wiki (currently links to https://charcoal-se.org/smokey).

Reported in chat by @JohnMiliter: https://chat.stackexchange.com/transcript/message/38567665#38567665

**Comment by CalvT** [comment]
Extra details...

`https://charcoal-se.org/smokey` redirects you to `https://charcoal-se.org/charcoal-se.org///smokey/` which is a 404.

If an extra `/` at the end is added it works - `https://charcoal-se.org/smokey/`

**Comment by j-f1** [comment]
Fixed in [`69f9e04`](https://github.com/Charcoal-SE/charcoal-jekyll-theme/commit/69f9e04f1ef6aa4123a6053a288f258be601a534) pending cache expiration.

**Comment by angussidney** [comment]
I've also updated Smokey's profile to prevent issues in the future.
