### ISSUE TITLE
Broken "wiki" link in smokeDetector's profile

### ISSUE THREAD

**Issue by JohnMiliter** [Charcoal-SE/charcoal-se.github.io#20]
It seems as though the "wiki" link in smokeDetector's profile is broken.

**Comment by tripleee** [comment]
I already reported this based on your report in chat.  Thanks for taking the time to follow up!

**Comment by tripleee** [comment]
Duplicates https://github.com/Charcoal-SE/charcoal-se.github.io/issues/19

**Comment by JohnMiliter** [comment]
I was on the "post issue" page when I had to leave, and I didn't realize it had already been posted when I returned. I am really sorry.

**Comment by angussidney** [comment]
Don't worry, just a simple communication issue :)
