### ISSUE TITLE
Search results have broken links

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/charcoal-se.github.io#23]
Clicking the magnifying glass in the top bar on https://charcoal-se.org/ and typing in a search term gets me many results which end up being broken links.

For example, searching for "moderator" gives me (mock-up):
* [Privileges](https://smokey/Privileges) (links to https://smoke/Privileges)
* [Chat Rooms](https://smokey/Chat-Rooms) (links to https://smokey/Chat-Rooms)
* [Meta: Who to ping](http://pings) (links to https://pings)
etc.

Screen shot:
<img width="1151" alt="screen shot 2017-09-15 at 12 35 06" src="https://user-images.githubusercontent.com/2160915/30476364-74a14adc-9a12-11e7-96ec-2462854412b7.png">

This is Firefox Nightly on MacOS Sierra.

**Comment by j-f1** [comment]
Thanks for pointing this out!
