### ISSUE TITLE
Fix the continuous integration for pull requests

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/charcoal-se.github.io#30]
Since [14 September 2017](https://github.com/Charcoal-SE/charcoal-se.github.io/pulls?q=is%3Apr+is%3Aclosed), continuous integration no longer works correctly in pull requests, failing with the error:

    Liquid Exception: The GitHub API credentials you provided aren't valid. in /_layouts/default.html

(or an error related to the fact that the PR was merged before the build ran again)

This should be fixed. so the CI indications on pull requests become reliable again incase we ever add a lint check to the project.

**Comment by j-f1** [comment]
I think it’s always been broken, it’s just that it didn’t make the build fail.
