### ISSUE TITLE
Emoji's broken on the userscript page

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/charcoal-se.github.io#43]
If I go to https://charcoal-se.org/scripts, I expect to see a fire emoji for the FIRE userscript.

It's not there:

![https://i.imgur.com/EsqtNn8.png](https://i.imgur.com/EsqtNn8.png)

Browser: Google Chrome: 8.0.3440.106
OS: Windows 10 64 bit

**Comment by j-f1** [comment]
Fixed by https://github.com/Charcoal-SE/charcoal-se.github.io/commit/7af1ccde2edfb7113a03dc693fc4c7ff7abcc4a4 & https://github.com/Charcoal-SE/charcoal-se.github.io/commit/b2f616a9dab9f2c50a7fae0fe8402c6a7e67ad99.
