### ISSUE TITLE
Linking directly to a heading highlights the whole page

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/charcoal-se.github.io#44]
If you hotlink to [a heading](https://charcoal-se.org/smokey/Privileges#reviewer-ms) on any page, an animated highlighting effect shows up, which is awesome. However, it highlights the *whole page* - not just the section of text under the heading.

![Section is highlighted](https://user-images.githubusercontent.com/4848802/45250809-c6328c80-b32a-11e8-8c5c-796152c02fde.PNG)

Potential hacktoberfest issue?

**Comment by ArtOfCode-** [comment]
Potential hacktoberfest issue for someone skilled with CSS - I failed to make this work when I originally implemented it.

**Comment by j-f1** [comment]
@flexbox That’s because on a few pages, I wrapped each section in a `<section>`. The current code highlights that.
