### ISSUE TITLE
Briefly document build automation

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/charcoal-se.github.io#51]
The Github Jekyll etc documentation is probably sufficient if you know what to look for, but untangling how this site is built for newcomers or occasional contributors is a challenge.

Maybe update the `README.md` with a very brief overview and pointers to proper documentation for more details.

This probably applies to the userscripts pages and various other Charcoal repos with nontrivial web components, too, but let's just keep this here.

**Comment by tripleee** [comment]
Somebody who is familiar with this from other projects could probably do a useful contribution. Tagging with Hacktober

**Comment by ArtOfCode-** [comment]
Removing [hacktoberfest]. As you said yourself - "untangling how this site is built for newcomers or occasional contributors is a challenge", which makes it kinda hard for a Hacktoberfest issue.

**Comment by iBug** [comment]
See if 333cc68acaab3fb3371e6e0795a432566982cdd3 is good.
