### ISSUE TITLE
jekyll-watch requires Ruby version >= 2.3.0

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/charcoal-se.github.io#52]
The build script on Travis depends on 2.2 but dependencies in the `Gemfile.lock` push this up to 2.3.0.

Should we drop `jekyll-watch`, or update the Travis reqs to Ruby 2.3?

**Comment by tripleee** [comment]
Thanks @j-f1

**Comment by j-f1** [comment]
(FYI I didn’t actually push that, it’s just that Travis has my API token to push with)

**Comment by iBug** [comment]
@j-f1 Maybe we should try Deploy Keys or generate an API token for Smokey's GH account
 (for automated jobs)?
