### ISSUE TITLE
Create a 'why is this domain watched/blacklisted' page for outsiders

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/charcoal-se.github.io#55]
Today we recieved an email from a company who was investigating the legitimacy of another company whose website was on our watchlist. They were unsure whether our watchlist entry meant that the company was a scam. [Further details can be viewed here](https://metasmoke.erwaysoftware.com/abuse/reports/81).

As per @tripleee's suggestion [here](https://chat.stackexchange.com/transcript/message/49331937#49331937), it would be a good if we had a page on our website designed especially for this kind of situation, so we can point outsiders to it in the future.

It should outline:
- [x] Why we add the sites to our watchlist (and why it doesn't necessarily mean that it's a scam)
- [x] The process for adding sites to the list (with links to blacklisting rules etc)
- [x] The process for removing sites from the list
- [x] How you can search for records/data/context relating to the domain
- [x] Some general tips for checking the legitimacy of a site/service based on our experience
- [x] Some sort of non-liability notice that states that this isn't tailored or legal advice on the legitimacy of a company/website

**Comment by iBug** [comment]
Are you on it? I am free *now* and I can come up with a draft for further discussion and refinement.

**Comment by angussidney** [comment]
Feel free, if you don't I'll probably get to it tomorrow

**Comment by iBug** [comment]
I think it's a good starting point at <https://github.com/Charcoal-SE/charcoal-se.github.io/blob/site/why-blacklisted.md> that I just created, but I'm having difficulty expanding it as well as completing it in a more formal tone.

Don't worry, it isn't published yet, see line 4.

**Comment by ArtOfCode-** [comment]
I'll run through and copy edit and expand that later, thanks @iBug.

**Comment by angussidney** [comment]
In https://github.com/Charcoal-SE/charcoal-se.github.io/commit/fd2de0485d973f45e0fbc267f027736b659ae83a I've fleshed out what @iBug wrote and slightly rearranged it so that it flows a bit better. I haven't read through it a second time yet to pick up all of the mistakes, so suggestions are welcome.

**Comment by angussidney** [comment]
Any objections to me publishing this?

**Comment by angussidney** [comment]
https://charcoal-se.org/why-blacklisted
