### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/charcoal-se.github.io#56]
Since at least this weekend, I am unable to obtain any search results on https://charcoal-se.org/

If I type in a search term in the magnifying glass in the upper right corner, I see the following messages in my JavaScript console:
```
(index):1 Unchecked runtime.lastError: The message port closed before a response was received.
box-90f3a29ef7448451db5af955688970d7.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
search-by-algolia.svg:1 Failed to load resource: the server responded with a status of 404 ()
```

**Comment by j-f1** [comment]
Confirmed fixed ✅

**Comment by tripleee** [comment]
@j-f1 Thanks for the quick fix, but I still don't see  search results  other than  sporadically.

For example, right now, typing "blacklist" into the search box behind the magnifying glass in the top-right corner at https://charcoal-se.org/ gets me nothing, just silence. (Typing "ping" into the search box does get me *something,* though it seems constrained to a single post, where there should be more than one.)

**Comment by tripleee** [comment]
I am again unable to obtain any search results on the site.

**Comment by tripleee** [comment]
Again, or still? Not able to get any results as of right now.

**Comment by j-f1** [comment]
It seems like the Algolia access token doesn’t have enough permissions. I’m currently re-running the latest build to see if the new permission I added helps.

**Comment by j-f1** [comment]
cc @iBug why is the site build run twice (once on Actions, once on Travis)?

**Comment by j-f1** [comment]
This should be fixed.

**Comment by iBug** [comment]
> cc @iBug why is the site build run twice (once on Actions, once on Travis)?

I originally wanted to migrate our site build from Travis to GH Actions and its in a partial state now. I suspended work on it after discovering that manually triggered Action builds can't use existing caches.
