### ISSUE TITLE
Cursed link to metasmoke API documentation

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/charcoal-se.github.io#57]
The page https://charcoal-se.org/ms has a link ostensibly to the metasmoke API documentation which doesn't work correctly. The first time I click, nothing happens; then, it displays a 404 page (the location bar shows /API-documentation where the link should apparently be to /ms/API-documentation). What's worse, clicking through causes the back button to stop working, and instead displaying `[object Object]` on every page on the site.

Hovering over the link shows me https://charcoal-se.org/ms/API-Documentation and copying that URL to the location bar allows me to view the destination page just fine. There's something wrong with the link itself.

The page source displays
```
<a href="API-Documentation">here</a>
```
I can't always repro, but entering the main site's start page, clicking through to the metasmoke wiki from near the end of the page, and then clicking the "here" link to the API documentation seems to repro every time for me (MacOS Mojave, Chrome 78.0.3904.97)

**Comment by iBug** [comment]
Tried @makyen 's instruction and it did reproduce the issue (Chrome 78), doesn't seem to be specific to any browser. I identified a possible cause and pushed a fix (that I believe is correct).
