### ISSUE TITLE
Farmhouse (Flovis) link broken

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/charcoal-se.github.io#68]
Under "More projects" on the site's top bar, there's a link to "Farmhouse (Flovis)", https://flovis.charcoal-se.org/. However, that site seems to be down.

If the site no longer exists, can this link please be removed? (Or is it just temporarily down? Submitting this as an issue instead of a direct PR to make sure that that's not the case.)

**Comment by user12986714** [comment]
It no longer exists, at least for now. See https://stackoverflow.com/c/charcoal/questions/606 .
