### ISSUE TITLE
User scripts page still links to Travis-CI.org; move the scripts build to another CI service

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/charcoal-se.github.io#78]
The [user scripts page](https://github.com/Charcoal-SE/charcoal-se.github.io/blob/site/scripts.md) still links to the old, deprecated https://travis-ci.org/ site, which is slated to be shut down on June 15.

The CI for the user scripts needs to be moved to another site before that date.

**Comment by iBug** [comment]
863e0a1daa6aacdf872e169c2c6b146967a3bfb9
