### ISSUE TITLE
Raw markdown visible on website (but looks correct in GitHub preview)

### ISSUE THREAD

**Issue by CoconutMacaroon** [Charcoal-SE/charcoal-se.github.io#94]
On [this wiki page](https://charcoal-se.org/smokey/Creating-new-commands), below the sentence "You can also manually return the non-privileged response if you want:", it looks like this:
![image](https://github.com/user-attachments/assets/f3ba302e-3e9b-4f1e-b6b1-88b2764c6297)

I can reproduce this in:
* Firefox 129 (adblocker disabled)
* Microsoft Edge, `Version 127.0.2651.105 (Official build) (64-bit)`

However, it renders fine in GitHub (on Firefox, with several extensions)
![image](https://github.com/user-attachments/assets/9e70f053-adcd-4ebe-b512-70f9b91a7658)

**Comment by iBug** [comment]
[Fixed here.](https://github.com/Charcoal-SE/SmokeDetector/wiki/Creating-new-commands/_compare/3d0f2cd068d6101755e80d56b1c05c8c0d92121c...eb131ad6819287e3298ae5792e42ea4d7ffb7ed7)
